#define DECLARE_CLIENT_FUNC(SUBFOLDER,FNAME) class FNAME {file = C_PATH(SUBFOLDER,FNAME); recompile = 1;}
#define DECLARE_CLIENT_FUNC_INIT(SUBFOLDER,FNAME) class FNAME {file = C_PATH(SUBFOLDER,FNAME); init=1; recompile = 1;}
#define DECLARE_CLIENT_FUNC_PREINIT(SUBFOLDER,FNAME) class FNAME {file = C_PATH(SUBFOLDER,FNAME); preInit=1; recompile = 1;}
#define DECLARE_CLIENT_FUNC_POSTINIT(SUBFOLDER,FNAME) class FNAME {file = C_PATH(SUBFOLDER,FNAME); postInit=1; recompile = 1;}
#define DECLARE_CLIENT_FUNC_PRESTART(SUBFOLDER,FNAME) class FNAME {file = C_PATH(SUBFOLDER,FNAME); postInit=1; recompile = 1;}

#define C_PATH(SUBFOLDER,FILENAME) \sgd\anarchy\an_client_c\client\functions\SUBFOLDER\FILENAME.sqf
